[2023-09-12 05:04:56,156] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: CallPostgreOperator.fetch_pageviews scheduled__2023-09-11T18:00:00+00:00 [queued]>
[2023-09-12 05:04:56,165] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: CallPostgreOperator.fetch_pageviews scheduled__2023-09-11T18:00:00+00:00 [queued]>
[2023-09-12 05:04:56,165] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-09-12 05:04:56,165] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-09-12 05:04:56,165] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-09-12 05:04:56,179] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fetch_pageviews> on 2023-09-11 18:00:00+00:00
[2023-09-12 05:04:56,183] {standard_task_runner.py:52} INFO - Started process 1770 to run task
[2023-09-12 05:04:56,185] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'CallPostgreOperator', 'fetch_pageviews', 'scheduled__2023-09-11T18:00:00+00:00', '--job-id', '1026', '--raw', '--subdir', 'DAGS_FOLDER/CallPostgreOperator.py', '--cfg-path', '/tmp/tmpugdxo8dr', '--error-file', '/tmp/tmp1zaamj0u']
[2023-09-12 05:04:56,186] {standard_task_runner.py:80} INFO - Job 1026: Subtask fetch_pageviews
[2023-09-12 05:04:56,302] {task_command.py:371} INFO - Running <TaskInstance: CallPostgreOperator.fetch_pageviews scheduled__2023-09-11T18:00:00+00:00 [running]> on host b18943745c0d
[2023-09-12 05:04:56,372] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=CallPostgreOperator
AIRFLOW_CTX_TASK_ID=fetch_pageviews
AIRFLOW_CTX_EXECUTION_DATE=2023-09-11T18:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-09-11T18:00:00+00:00
[2023-09-12 05:04:56,373] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-09-12 05:05:00,014] {python.py:173} INFO - Done. Returned value was: None
[2023-09-12 05:05:00,034] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=CallPostgreOperator, task_id=fetch_pageviews, execution_date=20230911T180000, start_date=20230912T050456, end_date=20230912T050500
[2023-09-12 05:05:00,056] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-09-12 05:05:00,109] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
