[2023-09-12 00:18:31,390] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: CallPostgreOperator.fetch_pageviews manual__2023-09-12T00:18:15.369394+00:00 [queued]>
[2023-09-12 00:18:31,401] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: CallPostgreOperator.fetch_pageviews manual__2023-09-12T00:18:15.369394+00:00 [queued]>
[2023-09-12 00:18:31,401] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-09-12 00:18:31,401] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-09-12 00:18:31,401] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-09-12 00:18:31,417] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fetch_pageviews> on 2023-09-12 00:18:15.369394+00:00
[2023-09-12 00:18:31,422] {standard_task_runner.py:52} INFO - Started process 22217 to run task
[2023-09-12 00:18:31,425] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'CallPostgreOperator', 'fetch_pageviews', 'manual__2023-09-12T00:18:15.369394+00:00', '--job-id', '908', '--raw', '--subdir', 'DAGS_FOLDER/CallPostgreOperator.py', '--cfg-path', '/tmp/tmpbr827jwx', '--error-file', '/tmp/tmpnr41fte2']
[2023-09-12 00:18:31,426] {standard_task_runner.py:80} INFO - Job 908: Subtask fetch_pageviews
[2023-09-12 00:18:31,486] {task_command.py:371} INFO - Running <TaskInstance: CallPostgreOperator.fetch_pageviews manual__2023-09-12T00:18:15.369394+00:00 [running]> on host b18943745c0d
[2023-09-12 00:18:31,560] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=CallPostgreOperator
AIRFLOW_CTX_TASK_ID=fetch_pageviews
AIRFLOW_CTX_EXECUTION_DATE=2023-09-12T00:18:15.369394+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-12T00:18:15.369394+00:00
[2023-09-12 00:18:31,562] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-09-12 00:18:33,961] {python.py:173} INFO - Done. Returned value was: None
[2023-09-12 00:18:33,978] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=CallPostgreOperator, task_id=fetch_pageviews, execution_date=20230912T001815, start_date=20230912T001831, end_date=20230912T001833
[2023-09-12 00:18:34,010] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-09-12 00:18:34,047] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
