[2023-09-11 11:52:10,560] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: listing_4_20.extract_gz scheduled__2023-09-10T03:00:00+00:00 [queued]>
[2023-09-11 11:52:10,572] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: listing_4_20.extract_gz scheduled__2023-09-10T03:00:00+00:00 [queued]>
[2023-09-11 11:52:10,573] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-09-11 11:52:10,573] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-09-11 11:52:10,573] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-09-11 11:52:10,595] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): extract_gz> on 2023-09-10 03:00:00+00:00
[2023-09-11 11:52:10,599] {standard_task_runner.py:52} INFO - Started process 546 to run task
[2023-09-11 11:52:10,603] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'listing_4_20', 'extract_gz', 'scheduled__2023-09-10T03:00:00+00:00', '--job-id', '346', '--raw', '--subdir', 'DAGS_FOLDER/listing_4_20.py', '--cfg-path', '/tmp/tmpsqmijh87', '--error-file', '/tmp/tmphzd8446v']
[2023-09-11 11:52:10,603] {standard_task_runner.py:80} INFO - Job 346: Subtask extract_gz
[2023-09-11 11:52:10,671] {task_command.py:371} INFO - Running <TaskInstance: listing_4_20.extract_gz scheduled__2023-09-10T03:00:00+00:00 [running]> on host b18943745c0d
[2023-09-11 11:52:10,747] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=listing_4_20
AIRFLOW_CTX_TASK_ID=extract_gz
AIRFLOW_CTX_EXECUTION_DATE=2023-09-10T03:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-09-10T03:00:00+00:00
[2023-09-11 11:52:10,749] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-09-11 11:52:10,750] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'gunzip --force /tmp/wikipageviews.gz']
[2023-09-11 11:52:10,760] {subprocess.py:85} INFO - Output:
[2023-09-11 11:52:10,765] {subprocess.py:92} INFO - gzip: /tmp/wikipageviews.gz: No such file or directory
[2023-09-11 11:52:10,766] {subprocess.py:96} INFO - Command exited with return code 1
[2023-09-11 11:52:10,783] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-09-11 11:52:10,787] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=listing_4_20, task_id=extract_gz, execution_date=20230910T030000, start_date=20230911T115210, end_date=20230911T115210
[2023-09-11 11:52:10,800] {standard_task_runner.py:97} ERROR - Failed to execute job 346 for task extract_gz (Bash command failed. The command returned a non-zero exit code 1.; 546)
[2023-09-11 11:52:10,814] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-09-11 11:52:10,857] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
